name: WakaTime Stats
on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 跑一次
  workflow_dispatch:      # 也可手动触发
jobs:
  update-stats:
    environment: env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master     # 社区常用 action
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: RadishoNeo
          BLOCKS: ░▒▓█                  # 进度条样式，可改
